name: GitHub metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: "master"
  workflow_dispatch:
jobs:

# The job below generates the images displayed on lowlighter/lowlighter
# You can reuse these steps if you want to have a profile page similar to mine.
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_traffic: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Shanghai
          config_order: base.header, isocalendar, base.repositories
          config_padding: 10%
          use_prebuilt_image: master 
          user: Sitoi
          plugin_followup: yes
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_url: https://sitoi.cn
          plugin_topics: yes
          plugin_topics_mode: mastered
      - name: Personal metrics (additional)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_skipped: lowlighter
          plugin_stargazers: yes
          config_timezone: Asia/Shanghai
          config_order: languages, pagespeed, habits, stargazers, stars
          use_prebuilt_image: master
          user: Sitoi
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 28
          plugin_people_size: 28
